workshops/README.md

Just added today's workshop to the descriptions of workshops. Nothing major.

added Workshop info March 20th

---

Announcements/announcements.md
_announcements/2020-11-03-announcement.md
_announcements/2020-12-03-announcement.md
_announcements/2021-01-04-announcement.md
_includes/announcement.html
_includes/announcement_list.html
blog/blog.md

This should address #39 
The announcements page just lists links to past announcements, not sure if we want more formatting?

Announcements updates

---

_announcements/2021-02-02-announcement.md

This commit adds the February Monthly HPC Update newsletter to the _announcements/ directory.

feb. announcement add

---

General/building-packages/building-packages.md
General/building-packages/modules.md
index.md

@chchang6 sorry realized the links were broken when the GH pages site got deployed, I must have had something cached locally when I tested.

fixing links

---

General/building-packages/building-packages.md

@diskwarrior dropping the Jekyll link for now

link fixes

---

languages/python/hpc_python.md
languages/python/numba/numba_demo.ipynb

Draft for HPC python resources

draft of hpc-python

---

_announcements/2021-03-03-announcement.md

This commit adds March 2021 HPC Newsletter/announcements.

March 2021 newsletter/announcements

---

Containers/tensorflow.md

Ks containers

---

General/building-packages/acquire.md
General/building-packages/building-packages.md
General/building-packages/config_make_install.md
General/building-packages/modules.md

adding navigation to building packages

---

_announcements/2021-04-06-announcement.md

This commit adds the April 2021 HPC Newsletter.

Pages news 042021

---

workshops/README.md

adding tf workshop

---

workshops/Optimized_TF/README.md
workshops/Optimized_TF/TFbenchmark.py
workshops/Optimized_TF/TFbenchmark.sh
workshops/Optimized_TF/how_to_build_notes/bazelbuild230.sh
workshops/Optimized_TF/how_to_build_notes/eagle_tensorflow_notes_23
workshops/Optimized_TF/py37tf20.yml
workshops/Optimized_TF/py37tf22.yml
workshops/Optimized_TF/py38tf23.yml
workshops/Optimized_TF/py38tf24.yml

Hello,
I am submitted this pull request for my upcoming tutorial on optimized TensorFlow builds for eagle.
Thank you!
-Paul Diaz

Eagle Optimized TensorFlow

---

Containers/singularity.md

Bringing in Singularity doc from the main repo. (removed peregrine section, minor version reference updates, otherwise the same.)

basic singularity

---

General/beginner/beginner.md
index.md

Minor changes to the main page

updates to the main page

---

_sass/custom/custom.css

Simple css to prevent the code blocks from wrapping (affects all pages)

custom css to prevent code block wrap

---

languages/python/conda.md
languages/python/python.md

simple fixes to some broken links/text in the python pages

fix python pages

---

_config.yml
_includes/analytics.html
_layouts/default.html

Adding google analytics using shared google account nrel.hpc.training (see hpc user ops for account access if needed)
Added default.html file from [just-the-docs](https://github.com/pmarsceill/just-the-docs/blob/master/_layouts/default.html) and added analytics scripts

add google analytics

---

languages/python/conda.md

Addresses the suggestion in #68

adding clone example

---

_announcements/2021-06-01-announcement.md

Adds June 2021 monthly HPC announcements.

june 2021 announcements

---

_announcements/2021-07-06-announcement.md

July 2021 HPC announcements/newsletter update.

july21 announcements

---

_announcements/2021-08-06-announcement.md

Adds August 2021 HPC Updates newsletter.

August 2021 newsletter

---

_announcements/2021-09-08-announcements.md

sept 2021 newsletter

---

workshops/README.md

Adding in the rest of the workshops for FY21

Workshop updates

---

README.md

Updating the README to reflect how to run the site locally now with mkdocs. 
Fixes: #112

adding a README with updated docker command

---

docs/Announcements/2022-01-05-announcement.md
mkdocs.yml

Adds January 2022 monthly updates

Jan 2022 monthly updates

---

docs/Documentation/Data-and-File-Systems/File-Systems/Lustre/lustrebestpractices.md
docs/Documentation/Data-and-File-Systems/File-Systems/index.md
docs/Documentation/Data-and-File-Systems/Transferring-Data/globus.md
docs/Documentation/languages/python/index.md

This is mostly a series of relatively typographic fixes for clarity and consistency. It also includes an edit to the Lustre best practices doc to fix a mis-statement about not using lustre for executables.

2022 doc updates 1

---

docs/Announcements/2022-02-02-announcement.md
mkdocs.yml

Adds February 2022 HPC Monthly Update.

feb 2022 newsletter

---

mkdocs.yml

Remove favicon and nrel logo 

---

docs/Documentation/Environments/building-packages/acquire.md
docs/Documentation/Environments/building-packages/config_make_install.md
docs/Documentation/Environments/building-packages/modules.md

These links didn't work, and the navigation links at the bottom of the page serve the same purpose.

Remove broken/repetitive links

---

docs/Documentation/languages/bash/bash-starter.md
mkdocs.yml

Intro to Bash Docs

---

docs/Announcements/2022-03-02-announcement.md
mkdocs.yml

Adds March 2022 announcements.

Announcements march2022

---

docs/Documentation/Systems/Swift/help.md
docs/Documentation/Systems/Swift/index.md
docs/Documentation/Systems/Swift/known.md
mkdocs.yml

Adds new Swift landing page, Support/Help page, and FAQ/Known Issues page.

Swift landing page, help, and FAQ/issues

---

docs/Documentation/Systems/Swift/running.md

PR #144 included some content that was already added to gh-pages, so I cherry-picked timk's latest commit.

TimK Auxsys additions

---

docs/Announcements/2022-04-06-announcement.md
mkdocs.yml

Adds April 2022 HPC updates/announcements.

april 2022 announcements

---

docs/Announcements/2022-05-04-announcement.md
mkdocs.yml

may 2022 announcements

---

docs/Documentation/Systems/Vermillion/running.md

- updated partition names to reflect existing partitions
- added a cores/node column to the partitions table
- edited module paths to point to existing modules
- updated the vasp documentation with working scripts to run VASP on CPUs and GPUs

Updated Vermilion Documentation

---

docs/Documentation/index.md

Fix homepage links

---

docs/Documentation/Systems/Vermillion/running.md

Old paths had a username in the path, new paths are in /nopt/nrel/apps

Update paths to vasp gpu executables

---

docs/Announcements/2022-08-11-announcement.md
mkdocs.yml

Adds August 2022 monthly newsletter.

August 2022 Newsletter

---

docs/Documentation/Systems/Vermillion/applications.md
docs/Documentation/Systems/Vermillion/modules.md
docs/Documentation/Systems/Vermillion/running.md

More or less a complete rewrite of Vermilion pages. Points to example scripts for simple builds/runs and scripts for Vasp.

rewrite of vermilion docs

---

README.md
general/Optimized_TF/README.md
languages/python/openai_rllib/simple-example-gpu/README.md

- Update links and references from `workshops` -> `general`.  Verified that the new links work.
- Remove entry for "Workshops and Presentations" on main README, which from what I can tell no longer exists.

Update references to `workshops` directory

---

docs/blog/2021-06-18-srun.md
docs/blog/2022-12-19-windows_ssh.md
mkdocs.yml

Content transfer for May and Aug. 2022 announcements

Transfer Windows SSH info to blog post

---

docs/Documentation/MachineLearning/ReinforcementLearning/index.md

Fix rendering of numbered list on Reinforcement Learning page.

Markdown fix

---

docs/Documentation/Applications/Matlab/batch.md
docs/Documentation/Applications/Matlab/index.md
docs/Documentation/Applications/Matlab/interactive.md
docs/Documentation/Applications/Matlab/parallel.md
docs/Documentation/Applications/Matlab/versions.md
docs/Documentation/Applications/matlab.md
mkdocs.yml

Closes #267.  Mostly a direct translation of existing content, with a couple of exceptions:
- Added "TODO" comments for a couple of links that don't yet exist on the branch and will need to be updated
- Fixed some instructions on the batch submission section that were out of date

Transfer Matlab documentation

---

docs/Documentation/Applications/lammps.md

Add LAMMPS Page

---

docs/Documentation/Systems/Swift/running.md

Rework of "Running on Swift" page with AU charge clarifications, partition info, spelling/grammar fixes

"Running on Swift" page updates

---

docs/blog/2022-03-05-local-io-performance.md
mkdocs.yml

Adds "local I/O performance" discussion from March 2022 as a blog entry.

local io performance blog

---

docs/Documentation/Managing_Data/Transferring_Files/winscp.md
docs/Documentation/getting_started.md

WinSCP CMS Content

---

docs/Documentation/Development/Languages/Python/dask.md
docs/Documentation/Development/Languages/Python/index.md

Clarified the introduction section, added installation section, updated the code examples, and rearranged the order (move dask-jobqueue in front of dask-mpi).  I tested all of the examples, but dask-mpi gave me some errors.  It looks like it may be related to some known issues on GitHub, so I added a "warning" block about this.

Update Dask content

---

docs/Documentation/Applications/ansys.md
docs/Documentation/Applications/comsol.md

This PR updates both the COMSOL and Ansys documentation.
closes #325, closes #323

Update COMSOL and Ansys Content

---

docs/Documentation/Data-and-File-Systems/File-Permissions.md
mkdocs.yml

UNIX file permissions explanation.

file permissions

---

docs/Documentation/Applications/wrf.md

First draft of wrf.md

---

docs/Documentation/Development/Compilers/rosetta_stone.md
docs/Documentation/Environment/shell.md
mkdocs.yml

replaced shell.md, added rosetta_stone.md, updated mkdocs.yml  The Rosetta Stone doc is rather long.  I have some ideas about that section we can discuss

replaced shell.md, added rosetta_stone.md, updated mkdocs.yml

---

general/markdown/README.md

HPC/general/markdown/README.md

fixed typo; explanitory->explanatory

---

docs/Documentation/Managing_Data/Transferring_Files/globus.md

416 - update order of globus.md

---

docs/Documentation/Systems/index.md

Ignore the past request made on the develop branch. Apologies for the inconvenience.

Kestrel system config info added

---

kestrel/vasp/makefile.include.intel_kestel_vasp5
kestrel/vasp/makefile.include.intel_kestrel_vasp6

Added a vasp5 and vasp6 sample makefile

---

docs/Friendly_User/Environments/tutorial.md
mkdocs.yml

add environments tutorial

---

docs/Documentation/Viz_Analytics/virtualgl_fastx.md

* Updates desktop client protocol from web to SSH. (https://github.com/NREL/HPC/issues/454)
* Updates client download links direct to StarNet's latest versions. (https://github.com/NREL/HPC/issues/436)

protocol update and client download links

---

docs/Documentation/Development/Libraries/petsc.md
mkdocs.yml

- Changes to mkdocs to add PETSc
- Content created for PETSc
tied to issue https://github.com/NREL/HPC/issues/358

PETSC section added

---

mkdocs.yml

Leaving VASP until transferred over

Remove friendly user docs

---

docs/Documentation/Environment/Building_Packages/acquire.md
docs/Documentation/Environment/Building_Packages/config_make_install.md
docs/Documentation/Environment/Building_Packages/index.md
docs/Documentation/Environment/Building_Packages/modules.md

- Index updated to include Kestrel
- Renaming of each sub-page
- Edits to the example to cover Kestrel

Kestrel updates for "build your own package" section

---

docs/Documentation/Applications/Matlab/batch.md
docs/Documentation/Applications/Matlab/interactive.md
docs/Documentation/Applications/Matlab/parallel.md
docs/Documentation/Machine_Learning/index.md

I updated the MATLAB docs from CMS to reflect the newer version of MATLAB, changed multiple instances of "Eagle" to "Kestrel," and updated interactive and batch job commands. 
For PyTorch and TensorFlow documentation I updated the module name for anaconda.

Added changes to MATLAB, PT, and TF docs

---

docs/Documentation/Systems/Kestrel/getting_started_kestrel.md

Getting Started on Kestrel page updates

---

docs/Documentation/Systems/Kestrel/index.md
docs/Documentation/Systems/Swift/index.md
docs/Documentation/Systems/Vermilion/index.md
docs/Documentation/Systems/index.md

Added Kestrel landing page, and fixed minor formatting for Swift and Vermilion.
modified:   docs/Documentation/Systems/Kestrel/index.md
modified:   docs/Documentation/Systems/Swift/index.md
modified:   docs/Documentation/Systems/Vermilion/index.md

258_Add System landing page for Kestrel kestrel

---

docs/Documentation/Managing_Data/Transferring_Files/globus.md

Added Kestrel endpoints and documentation about current issues with globus.	
modified:   docs/Documentation/Managing_Data/Transferring_Files/globus.md

Globus Documentation Update

---

kestrel/apptainer/defs/add.def
kestrel/apptainer/defs/alpine.def
kestrel/apptainer/defs/app_base.def
kestrel/apptainer/defs/apptainer.def
kestrel/apptainer/defs/intel.def
kestrel/apptainer/defs/intel_old.def
kestrel/apptainer/defs/mods_intel.def
kestrel/apptainer/defs/mpich_ch3.def
kestrel/apptainer/defs/mpich_ch4.def
kestrel/apptainer/defs/openmpi.save.def
kestrel/apptainer/defs/openmpi_x.def
kestrel/apptainer/defs/sif2def
kestrel/apptainer/defs/small.def
kestrel/apptainer/defs/spack.def
kestrel/apptainer/defs/ubuntu-mpi.def
kestrel/apptainer/script
kestrel/apptainer/tymer

Apptainer example scripts for Apptainer docs (PR #517) contributed by Tim K.

Add apptainer scripts

---

docs/Documentation/Systems/Kestrel/filesystems.md

Kestrel Filesystem

---

docs/Documentation/Systems/Kestrel/index.md

modified:   Systems/Kestrel/index.md

Add external login node info to Kestrel system landing page 

---

docs/Documentation/Development/Languages/Python/index.md
docs/Documentation/Environment/Customization/conda.md

Update Python Landing page

---

docs/Documentation/Applications/index.md
mkdocs.yml

Applications Landing Page

---

docs/Documentation/Applications/vasp.md

Added vasp gpu script for swift.

Added documentation for Swift vasp gpu module (vasp/openacc).

---

docs/Documentation/Applications/index.md

Add links to applications page table 

---

docs/Documentation/Applications/gurobi.md
docs/Documentation/Development/Languages/Julia/index.md

Update Gurobi documentation and add updated module info for Julia.

Update Gurobi documentation

---

docs/Friendly_User/Applications/pytorch.md

I've added documentation on how to do a basic install of PyTorch, how to submit a batch job, and have included a basic example the user can run and modify to test functionality and observe multi-GPU performance.

added pytorch documentation

---

docs/Friendly_User/BuildandRun/gpubuildandrun.md

Discusses build and run scripts for H100 nodes. It points to a repo with scripts and source.  We may want to move the target to another repo.

Build and Run on H100 GPUs

---

docs/Documentation/Managing_Data/localstorage.md

Added clarifying comments detailed in Issue 635.

add clarifying comments

---

docs/Friendly_User/BuildandRun/gpubuildandrun.md
docs/Friendly_User/index.md

I found some typos under the Kestrel GPU Friendly Users pages and fixed them.

Fixing typos

---

docs/Documentation/Applications/gaussian.md

A new example script was sent by Hai Long, who is traveling and cannot update it himself. This PR replaces the old example script with Hai's new one to work on Kestrel

update gaussian example script

---

docs/Documentation/Development/Jupyter/index.md

Modified https://nrel.github.io/HPC/Documentation/Development/Jupyter/#auto-launching-on-eagle-with-an-sbatch-script to talk about new Kestrel Jhub scripts

modify section about Jhub scripts

---

docs/Documentation/Development/Programming_Models/gpu_hpc.md
mkdocs.yml

First section: General GPU intro, including example scripts for Kestrel, Swift, and Vermilion
Second section: Numba example showing differences between CPU and GPU implementations of matrix multiplication

GPUs for HPC

---

docker-examples/README.md
docker-examples/cuda-12.4/Dockerfile
docker-examples/simple-python3/Dockerfile

Adding some Dockerfiles to reference for both the container documentation and the upcoming "Using GPUs with software containers" training next week

dockerfile examples

---

docs/Documentation/Machine_Learning/Containerized_TensorFlow/index.md

Regarding https://github.com/NREL/HPC/issues/674

Update TensorFlow container documentation

---

docs/Documentation/Development/Languages/Python/dask.md
docs/Documentation/Machine_Learning/Containerized_TensorFlow/index.md

Added some extra details where I could and removed any Eagle-specific things I noticed. I also have the examples use the "shared" partition now, because I think frameworks like dask are a natural fit for that kind of setup

Dask updates for Kestrel

---

docs/Documentation/Applications/comsol.md

The lmstat.comsol is available now, the users don't need to create their own command.

Update COMSOL documentation

---

docs/Documentation/Environment/Customization/conda.md

Add note about settings in condarc being overwritten by module as requested by user.

Conda Updates

---

docs/Documentation/Applications/Matlab/batch.md
docs/Documentation/Machine_Learning/index.md

Updated GPU instructions for PyTorch, and sbatch files for MATLAB

Updates to Matlab and Pytorch docs

---

docs/Documentation/Applications/index.md
docs/Documentation/Applications/mace.md
mkdocs.yml

New application page for MACE added.

MACE apps page added

---

docs/Documentation/Applications/starccm.md

Fixed the typo in the documentation.

Update starccm documentation

---

docs/Documentation/Applications/alphafold.md
docs/Documentation/Applications/index.md
mkdocs.yml

Initial commit for documentation describing how to use the new AlphaFold3 module on Kestrel.

AlphaFold documentation

---

docs/Documentation/Applications/amrwind.md

Some suggested hbw updates for the AMR-Wind page. Would appreciate @arswalid @gbetrie @yandthj 's reviews!

AMR-Wind hbw updates

---

docs/Documentation/Development/VSCode/vscode.md

Updates the ssh config wildcard to capture newer GPU nodes.

ssh wildcard update

---

docs/Documentation/Applications/comsol.md

Updates directions for compute node ssh -Y with Comsol.

Update directions for compute node ssh -Y

---

docs/Documentation/Managing_Data/localstorage.md
docs/Documentation/Systems/Kestrel/Running/example_sbatch.md
docs/Documentation/Systems/Kestrel/Running/index.md

Update for debug partition changes and addition of nvme partition

Partition Updates

---

docs/Documentation/Applications/amrwind.md
docs/Documentation/Applications/index.md
docs/Documentation/Applications/openfast.md
mkdocs.yml

- Expand on AMR-Wind documentation, adding updated build and run scripts
- Adds OpenFAST and FAST.Farm documentation, including build instructions and run examples

Documentation for AMR-Wind and OpenFAST/FAST.Farm

---

docs/Documentation/Development/Programming_Models/gpu_hpc.md

Hi Haley, I'm adding a quick blurb on `nvidia-smi` to the "GPUs for HPC" page. Please let me know what you think of the simple example use case. 
For more complicated profiles on jobs needing >2 nodes, people can use our [GPU Monitor utility](https://github.nrel.gov/hpc-apps/gpu_monitor) (which is based on `nvidia-smi`), but it is still under some development and is not yet documented in a place that external users can see, so I didn't mention it here (at least yet).
Thanks!

generic nvidia-smi info

---

docs/Documentation/Applications/ansys.md

The Ansys documentation is updated to include the GPU utilization.

Update ansys.md to include GPU jobs
