NREL/HPC

_announcements/2020-11-06-announcement.md
_announcements/2020-12-03-announcement.md
_announcements/2021-01-04-announcement.md

This commit updates the Monthly Announcements, to add December 2020 and January 2021. It also removes what looks like an incomplete draft (2020-11-06).

announcements update

---

DataMovement/TransferringData/FileZilla.md
DataMovement/TransferringData/file-transfers.md
DataMovement/TransferringData/globus.md
DataMovement/TransferringData/transferringdata.md
DataMovement/datamovement.md
General/beginner/file-transfers.md

Draft update for the filetransfers docs. Updated Peregrine -> Eagle and alloc -> hours_report.
**Outstanding work**

filetransfers

---

Jupyter/jupyter.md
Jupyter/jupyterhub.md

Moving Jupyter to a top level category. Also added a link to the JupyterHub doc on NREL's site.

Jupyter reorg

---

IO/Lustre/lustre.md
IO/Lustre/lustrebestpractices.md
IO/filesystemsio.md

Reorg so Filesystems and I/O are top level category, split Lustre out into a sub category.

Filesystems and I/O 

---

languages/python/jupyter/README.md
languages/python/jupyter/auto_launch_jupyter.sh
languages/python/jupyter/create_env.sh
languages/python/jupyter/sbatch_jupyter.sh

This PR adds a couple of scripts and documentation for automating the process of launching a jupyter lab instance on an eagle compute node.
The `auto_launch_jupyter.sh` script is a bit of a beast but we've used it with success in the Transportation (5400/MBAP) group. Maybe someone with bash expertise could review to see if there are any gaping holes.
I reviewed the contributing guidelines but this is my first PR in this repository so I apologize if I missed anything!

Adding scripts for launching jupyter lab via slurm

---

Systems/systems.md

No GPUs, nodes are 484 instead of 40, etc.

Swift updates.

---

applications/gaussian/large/cpu1/g16.slurm
applications/gaussian/large/cpu2/g16.slurm
applications/gaussian/large/gpu1/g16.slurm
applications/gaussian/large/gpu2/g16.slurm
applications/gaussian/medium/cpu1/g16.slurm
applications/gaussian/medium/cpu2/g16.slurm
applications/gaussian/medium/gpu1/g16.slurm
applications/gaussian/medium/gpu2/g16.slurm
applications/gaussian/small/cpu1/g16.slurm
applications/gaussian/small/cpu2/g16.slurm
applications/gaussian/small/gpu1/g16.slurm
applications/gaussian/small/gpu2/g16.slurm
general/beginner/how-to-transfer-files/README.md
general/beginner/how-to-transfer-files/globus.md
general/beginner/how-to-transfer-files/winscp.md
general/beginner/markdown/RenameStep2.md
general/intermediate/software-environment-basics/README.md
general/intermediate/software-environment-basics/singularity-how-to.md
languages/c/README.md
languages/fortran/README.md

Replaced references to "Peregrine" with "Eagle". However, there are a few files with outdated instructions where "peregrine" is referenced in code. Replacing these will require updating those instructions as well.

Remove references to Peregrine and update documentation with Eagle content

---

docs/Documentation/Software_Tools/FastX/fastx.md
mkdocs.yml

Initial commit for documentation on using the DAV FastX nodes on Eagle.

fastx docs

---

docs/Documentation/Systems/Swift/filesystems.md
mkdocs.yml

This commit adds a documentation outline for the Swift filesystems, including explanations of /projects and /scratch.

Swift filesystems

---

docs/blog/2021-05-06-tf.md

It's the "tutorial materials" link at the bottom of this page: https://nrel.github.io/HPC/blog/2021-05-06-tf/

Update "Optimized_TF" link in blog post

---

docs/Documentation/Applications/gurobi.md

Closes #266.  Transferring from CMS was straightforward.  One reference to Eagle was changed to make the documentation more generic: "Eagle hosts 6 general use ... licenses" -> "NREL hosts 6 general use ... licenses".  Link to the Gurobi Getting Started Portal was out of date and has been replaced by two new links: Gurobi Resource Center and Documentation.

Transfer documentation for Gurobi

---

docs/Documentation/Development/Build_Tools/cmake.md

Since CMake is a standard tool, I think we can keep this short and simply reference existing documentation and provide the necessary info about how to load the module.

Add content for CMake

---

docs/Documentation/Development/Languages/c++.md

This adds basic C++ content with a minimum hello world example and some information on toolchains/modules.
My preference is to avoid duplicating content for subtopics, so for example I have linked to the MPI page instead of trying to hash out all of the toolchain/MPI lib combinations.  I also prefer to avoid making this a language tutorial, since C++ is so large in scope (especially with the standard library).

Add C++ content

---

docs/Documentation/Development/Languages/r.md

Closes #477 
The primary changes are to generalize the usage information so that it is not specific to Eagle, but to provide instructions for Kestrel where specific examples are given.  The main difference is that on Eagle, R was available in the base conda environment, whereas on Kestrel the user would create a new conda env that contains R.

Update R documentation for Kestrel

---

docs/Documentation/Development/Build_Tools/cmake.md

Set the compiler environment variables at configure time instead of when running Make.  This enables the CMake configuration to identify the compilers.

Minor update to CMake example

---

docs/Documentation/Applications/vasp.md

Ported VASP friendly users documentation to main page and cut down text overall

VASP main page updates

---

docs/Documentation/Systems/Vermilion/running.md

1. By running sinfo, it shows there are 16 GPU nodes.
2. Is there QoS Factor for vermillion? Will the normal and high priority jobs be charged equally?

Correction and updates to the documentation of Vermillion

---

docs/Documentation/Systems/Kestrel/Environments/index.md
docs/Documentation/Systems/Kestrel/running.md

Update the Performance Recommendations section in Running Jobs to match the transition page, and add a note on OpenMPI performance on the Kestrel/environments index page.

Update performance recommendation section in running jobs

---

applications/spark/README.md
applications/spark/config
applications/spark/docker/python/Dockerfile
applications/spark/docker/r/Dockerfile
applications/spark/python.md
applications/spark/r.md
applications/spark/slurm_scripts/batch_job.sh
applications/spark/slurm_scripts/batch_jupyter.sh
applications/spark/slurm_scripts_with_resource_monitoring/batch_job.sh
applications/spark/slurm_scripts_with_resource_monitoring/batch_jupyter.sh
applications/spark/spark_scripts/common.sh
applications/spark/spark_scripts/configure_and_start_spark.sh
applications/spark/spark_scripts/configure_spark.sh
applications/spark/spark_scripts/create_config.sh
applications/spark/spark_scripts/start_container.sh
applications/spark/spark_scripts/start_spark_cluster.sh
applications/spark/spark_scripts/start_spark_worker.sh
applications/spark/spark_scripts/stop_container.sh
applications/spark/spark_scripts/stop_spark_cluster.sh
applications/spark/tests/README.md
applications/spark/tests/batch_job.sh.template
applications/spark/tests/run_tests.sh

There are two sets of changes in this pull request:
1. Update paths, commands, and instructions for Kestrel. There are also some general documentation improvements.
2. Add the new script, `configure_and_start_spark.sh`, to allow the user to get the cluster running in a single command instead of three. The actual functionality didn’t change much.
I have tested the scripts on Eagle and Kestrel. The included test runs on Kestrel.

Update scripts and instructions for Kestrel

---

docs/Documentation/Development/VSCode/vscode.md
mkdocs.yml

Adds instructions for generating an SSH key and using it with Kestrel or Eagle, adding a Host entry to the ssh config file, and using the VSC Remote SSH extension to connect.

Connecting to HPC Systems with VSCode

---

applications/spark/spark_scripts/configure_and_start_spark.sh
applications/spark/spark_scripts/create_config.sh
applications/spark/spark_scripts/start_spark_cluster.sh

Fixes #603. The scripts were not exiting-on-error in all situations.

Ensure that the Spark scripts exit if a command fails.

---

docs/Documentation/Systems/Swift/running.md
docs/Documentation/Systems/index.md

Systems page:
* Now includes Swift GPU nodes.
Running on Swift page:
* Adds --gres=gpu instructions to request GPU nodes.
* Adds section on shared node AU calculations.
* Removes VASP, Jupyter, and Julia instructions (made redundant by separate pages.)

Swift system gpu

---

applications/spark/README.md
applications/spark/conf/spark-env.sh
applications/spark/spark_scripts/configure_and_start_spark.sh
applications/spark/spark_scripts/create_config.sh

The Spark scripts were broken by two recent changes to Kestrel:
- /tmp/scratch is no longer writable.
- Apptainer images were moved to a new location.
I noticed that several other documentation pages and scripts are affected by the change to /tmp/scratch. Is there any chance that `$LOCAL_SCRATCH` (only on Kestrel compute nodes with local storage) can be changed to `$TMPDIR` (instead of /tmp/scratch)? It seems problematic to have that environment variable point to a read-only location.

Update directories in Spark scripts to match Kestrel changes

---

docs/Friendly_User/gpu_containers.md

I realized there was a tab indent typo in the tensor_test.py example for Friendly Users GPU containers. This commit fixes the typo so the script can be run as-is.

tab indent typo fix for example TensorFlow script

---

docs/Documentation/Development/Jupyter/index.md

Documentation cleanup to include Kestrel-Jhub, remove Europa and Eagle references.

Jupyter updates for Kestrel

---

docs/Documentation/Development/Programming_Models/gpu_hpc.md

- Following some discussion with Haley and Olivia, removing CUDA_VISIBLE_DEVICES to avoid confusion as it is generally unnecessary with Slurm. SLURM_JOB_GPUS will reflect the real GPU device IDs in a given job if are multiple users running jobs on one node, so that variable should be preferred anyway.
- Also minor typo fix in my example Numba code

remove CUDA_VISIBLE_DEVICES

---

docker-examples/cuda-12.4/Dockerfile

Removing references to `wget --no-check-certificate` as it is not really the best practice. Users can add this if they are on-site using the internal VPN and are having issues with the certificates

Minor updates to Dockerfile example

---

docs/Documentation/Applications/ipopt.md
docs/Documentation/Development/Libraries/hsl.md

Updates the installation instructions for IPOPT + HSL linear solvers from Eagle to Kestrel

Update IPOPT and HSL documentation for Kestrel

---

applications/spark/README.md
applications/spark/spark_scripts/common.sh
applications/spark/spark_scripts/configure_and_start_spark.sh
applications/spark/spark_scripts/configure_spark.sh
applications/spark/spark_scripts/create_config.sh
applications/spark/spark_scripts/start_container.sh
applications/spark/spark_scripts/start_spark_cluster.sh
applications/spark/spark_scripts/stop_container.sh
applications/spark/spark_scripts/stop_spark_cluster.sh
applications/spark/tableau.md

This PR adds an option to the Spark startup scripts to to use PostgreSQL for the optional Hive Metastore. The default metastore allows only one client at a time. If Postgres is used, multiple clients can connect. One of my applications that uses these scripts needs simultaneous connections through one Python client and one Hive client.
The scripts download the latest PostgreSQL Docker container through Apptainer and start it on the same compute node as the Spark master process.
I also updated the Spark container image to use the newest version of Spark.

Update Spark scripts to support multiple client connections to the Hive metastore

---

docs/Documentation/Systems/Swift/running.md

Bill recently removed the 'parallel' partition on Swift because it was the exact same nodelist/etc. as 'standard'. I believe this is the only reference to 'parallel' in our docs.

remove reference to parallel partition on swift

---

applications/plexos/RunFiles/submit_enhanced.sh
applications/plexos/RunFiles/submit_job_array.sh
applications/plexos/RunFiles/submit_plexos.sh
applications/plexos/RunFiles/submit_simple.sh

Removes Gurobi import from example PLEXOS scripts.

update remove gurobi modules from plexos run scripts.

---

docs/Documentation/Development/Languages/Python/dask.md

This PR adds a section to the Dask help. The addition explains the usage of Batch Runners on Kestrel with examples. (https://jobqueue.dask.org/en/stable/runners-overview.html)

Dask help - Addd batch runner section

---

docs/Documentation/Applications/Plexos/setup_plexos.md

The license server for PLEXOS has changed. We needed to update the instructions online to reflect the same.

update PLEXOS license server address and port in EE_Reg.xml.

---

docs/Documentation/Applications/lammps.md

Added documentation for running LAMMPs on the HBW nodes and gave a sample script - I made sure to include the MPICH_OFI_NIC_POLICY and CPUBINDING variables in there, as that gives extra performance gains on the high-bandwidth nodes. In addition, I kept the job-array formatting of the slurm script in there, so that users can see that they wouldn't necessarily need to submit the same job 5 separate times.

adding LAMMPs HBW partition documentation/example script

---

docs/Documentation/Slurm/batch_jobs.md
docs/Documentation/Slurm/monitor_and_control.md
docs/Documentation/Systems/Kestrel/Running/kestrel_job_priorities.md

Also updated the monitor_and_control page to remove Eagle outputs (replaced with Kestrel outputs).

Document standby info for Slurm/Kestrel pages

---

docs/Documentation/Slurm/monitor_and_control.md
docs/Documentation/Systems/Kestrel/Running/kestrel_job_priorities.md

Resolves #760
Addresses adding `sprio` mention to the Kestrel Priorities page. 
Also, adds new example results of `sprio` that include the Fairshare column for completeness.

Update Kestrel Priorities Page and Slurm Monitor and Control page

---

docs/Documentation/Systems/Kestrel/Filesystems/index.md

Does not seem to be any other mentions of the snapshots or backups anywhere else. 
I noticed that there is [a section in the Swift filesystem docs](https://github.com/NREL/HPC/blob/68599fbc61b2712d521dfbc4ffceab7392500426/docs/Documentation/Systems/Swift/filesystems.md?plain=1#L50) directly clarifying there is not backups or snapshots on Swift. Should something be added to this Kestrel section as well?

Clarifying No snapshots/backups on Kestrel HFS

---

docs/Documentation/Machine_Learning/Reinforcement_Learning/index.md
docs/Documentation/Machine_Learning/index.md

Found that a bunch of links were pointing at a repo of a contributor. Retargeted all those links to be pointing at this repo's version of those links.
I couldn't find similar files in the gh-pages branch, so I assume that the best place to point would be master. Please correct me if I'm wrong.

Update Reinforcement Learning Hyperlinks

---

docs/Documentation/Development/Languages/Python/KestrelParallelPythonJupyter/pyEnvsAndLaunchingJobs.md

Missing quotes caused the content to render as normal text beginning with '??? example'.

rendering fix for type 'example'. Double quotes were missing

---

docs/Documentation/Environment/shell.md

Did a bunch of updates on the Shell Documentation to fix typos, readability issues, and update documentation.
Overall, the goal was to make the documentation easier to read and understand.
Some of this is subjective. Feel free to make edits or undo changes as you see fit.

Editorial Work on Shell Documentation
